////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         https://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

[#release-notes-2-24-1]
== 2.24.1

Release date:: 2024-09-24

This release contains mainly bug fixes of problems encountered with the thread context map, logger registry and configuration reloading.

It also enhances integration tests to use Docker images of the most recent releases of MongoDB and Elastic Search.


[#release-notes-2-24-1-changed]
=== Changed

* Rework `LoggerRegistry` to make it `MessageFactory`-namespaced. This effectively allows loggers of same name, but different message factory. (https://github.com/apache/logging-log4j2/pull/2936[2936])
* Enable Docker-based tests in CI for JSON Template Layout (https://github.com/apache/logging-log4j2/pull/2953[2953])

[#release-notes-2-24-1-fixed]
=== Fixed

* Switch MongoDB tests to use Docker. (https://github.com/apache/logging-log4j2/issues/2229[2229])
* Fix reloading of the configuration from an HTTP(S) source (https://github.com/apache/logging-log4j2/issues/2937[2937])
* Fix `putAll()` in the default thread context map implementation (https://github.com/apache/logging-log4j2/pull/2942[2942])

[#release-notes-2-24-1-updated]
=== Updated

* Update `org.apache.logging:logging-parent` to version `11.3.0`
